const path=location.pathname.replace(/\/$/,'')||'/';const section=path.split('/').filter(Boolean).at(-1)||'';
const nav=document.querySelector('.nav');const menu=document.querySelector('.menu');
if(menu)menu.addEventListener('click',()=>{menu.classList.toggle('open');nav.classList.toggle('open');menu.setAttribute('aria-expanded',menu.classList.contains('open'))});
document.querySelectorAll('.nav a').forEach(a=>{const target=new URL(a.href,location.href).pathname.split('/').filter(Boolean).at(-1)||'';if(target===section)a.classList.add('active')});
const audio=document.querySelector('#audio');const play=document.querySelector('.play');
if(play&&audio){play.addEventListener('click',()=>{if(audio.paused){audio.play();play.textContent='Ⅱ';play.setAttribute('aria-label','Pause')}else{audio.pause();play.textContent='▶';play.setAttribute('aria-label','Play')}});audio.addEventListener('timeupdate',()=>{const pct=audio.duration?audio.currentTime/audio.duration*100:0;document.querySelector('.timeline i').style.width=pct+'%';document.querySelector('.time').textContent=format(audio.currentTime)});audio.addEventListener('ended',()=>{play.textContent='▶'});}
function format(t){if(!Number.isFinite(t))return '0:00';return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')}
document.querySelectorAll('input[type=file]').forEach(input=>input.addEventListener('change',()=>{const file=input.files[0];if(!file)return;const url=URL.createObjectURL(file);if(input.accept.includes('audio')){audio.src=url;document.querySelector('.track-title').textContent=file.name.replace(/\.[^.]+$/,'');document.querySelector('.track-meta').textContent='Private listening copy';play.textContent='▶';}else{const video=document.querySelector('#video');video.src=url;video.parentElement.classList.add('has-video');video.play();document.querySelector('#film-name').textContent=file.name.replace(/\.[^.]+$/,'');}input.closest('.upload-card')?.querySelector('.file-note')?.replaceChildren(document.createTextNode(file.name+' · loaded for this visit'));}));
document.querySelectorAll('.mini').forEach((m,i)=>m.addEventListener('click',()=>{document.querySelector('.art-info h2').textContent=i?'The Quiet Measure':'After the Bell';document.querySelector('.catalog').textContent=i?'Study II · date withheld':'Study I · date withheld'}));
